name: Continuous integration

on:
  pull_request:
    types: [push, synchronize, opened, reopened]
  push:
    branches: [main]

jobs:
  clippy_check:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features compression,tokio-comp
  build_and_test:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check with tokio-comp
        run: cargo check --features tokio-comp
      - name: Check with async-std-comp
        run: cargo check --features async-std-comp
      - name: Check with async-std-comp and compression
        run: cargo check --features async-std-comp,compression
      - name: Check with tokio-comp and compression
        run: cargo check --features tokio-comp,compression
      - name: Test with tokio-comp
        run: cargo test --features tokio-comp
      - name: Test with async-std-comp
        run: cargo test --features async-std-comp
      - name: Test with async-std-comp and compression
        run: cargo test --features async-std-comp,compression
      - name: Test with tokio-comp and compression
        run: cargo test --features tokio-comp,compression
      - name: Clean
        run: cargo clean
